version: '3'
services:
    pubsubapi:
        image: 'pubsub-api'
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
        - '3000:3000'
        environment:
        - NODE_ENV=development
        - PORT=3000
        - DATABASE_URL=mongodb://localhost:27017/pub_sub_db
